import { setUncaughtExceptionCaptureCallback } from "process";
import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Adams",
      email: "okeyoadams@gmail.com",
      password: bcrypt.hashSync("12345678"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "ochanjijane@gmail.com",
      password: bcrypt.hashSync("12345678"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Shirt",
      slug: "shirt",
      category: "shirts",
      image: "/assets/Screenshot (206).png",
      price: 10,
      brand: "nike",
      rating: 5,
      reviews: 12,
      stock: 34,
      description: "a multicolored shirt that fits your body well",
    },
    {
      name: "Shorts",
      slug: "shirt",
      category: "shirts",
      image: "/assets/Screenshot (206).png",
      price: 10,
      brand: "nike",
      rating: 5,
      reviews: 12,
      stock: 34,
      description: "a multicolored shirt that fits your body weel",
    },
    {
      name: "pants",
      slug: "shirt",
      category: "shirts",
      image: "/assets/Screenshot (206).png",
      price: 10,
      brand: "nike",
      rating: 5,
      reviews: 12,
      stock: 34,
      description: "a multicolored shirt that fits your body weel",
    },
    {
      name: "socks",
      slug: "shirt",
      category: "shirts",
      image: "/assets/Screenshot (206).png",
      price: 10,
      brand: "nike",
      rating: 5,
      reviews: 12,
      stock: 34,
      description: "a multicolored shirt that fits your body weel",
    },
    {
      name: "t-shirt",
      slug: "shirt",
      category: "shirts",
      image: "/assets/Screenshot (206).png",
      price: 10,
      brand: "nike",
      rating: 5,
      reviews: 12,
      stock: 34,
      description: "a multicolored shirt that fits your body weel",
    },
    {
      name: "jacket",
      slug: "shirt",
      category: "shirts",
      image: "/assets/Screenshot (206).png",
      price: 10,
      brand: "nike",
      rating: 5,
      reviews: 12,
      stock: 34,
      description: "a multicolored shirt that fits your body weel",
    },
  ],
};

export default data;
