import { setUncaughtExceptionCaptureCallback } from "process";

const data = {
  products: [
    {
      name: "Shirt",
      slug: "shirt",
      category: "shirts",
      image: "/assets/Screenshot (206).png",
      price: 10,
      brand: "nike",
      rating: 5,
      reviews: 12,
      stock: 34,
      description: "a multicolored shirt that fits your body well",
    },
    {
      name: "Shorts",
      slug: "shirt",
      category: "shirts",
      image: "/assets/Screenshot (206).png",
      price: 10,
      brand: "nike",
      rating: 5,
      reviews: 12,
      stock: 34,
      description: "a multicolored shirt that fits your body weel",
    },
    {
      name: "pants",
      slug: "shirt",
      category: "shirts",
      image: "/assets/Screenshot (206).png",
      price: 10,
      brand: "nike",
      rating: 5,
      reviews: 12,
      stock: 34,
      description: "a multicolored shirt that fits your body weel",
    },
    {
      name: "socks",
      slug: "shirt",
      category: "shirts",
      image: "/assets/Screenshot (206).png",
      price: 10,
      brand: "nike",
      rating: 5,
      reviews: 12,
      stock: 34,
      description: "a multicolored shirt that fits your body weel",
    },
    {
      name: "t-shirt",
      slug: "shirt",
      category: "shirts",
      image: "/assets/Screenshot (206).png",
      price: 10,
      brand: "nike",
      rating: 5,
      reviews: 12,
      stock: 34,
      description: "a multicolored shirt that fits your body weel",
    },
    {
      name: "jacket",
      slug: "shirt",
      category: "shirts",
      image: "/assets/Screenshot (206).png",
      price: 10,
      brand: "nike",
      rating: 5,
      reviews: 12,
      stock: 34,
      description: "a multicolored shirt that fits your body weel",
    },
  ],
};

export default data;
